apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: harsha
spec:
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: asia-docker.pkg.dev/${GCP_PROJECT_ID}/hclhackathonshiva/order-service:${github.sha}
        env:
          - name: TZ
            value: "Asia/Kolkata"        
          - name: ENV
            value: dev
          - name: PORT
            value: "80"
        ports:
          - containerPort: 80
        resources:
          limits:
            cpu: "300m"
            memory: "500Mi"
          requests:
            cpu: "200m"
            memory: "200Mi"
      imagePullSecrets:
      - name: serviceaccount            
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: harsha
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: order-service    