apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient
  template:
    metadata:
      labels:
        app: patient
    spec:
      containers:
      - name: patient
        # Matches your Artifact Registry path
        image: us-central1-docker.pkg.dev/flash-spot-478811-m2/hackathon-repo/patient-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: patient-service
spec:
  type: LoadBalancer
  selector:
    app: patient
  ports:
  - port: 80
    targetPort: 8080