apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
  namespace: harsha
  labels:
    app: patient-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      containers:
        - name: patient-service
          image: asia-docker.pkg.dev/${GCP_PROJECT_ID}/hclhackathonshiva/patient-service:${github.sha}
          imagePullPolicy: Always
          ports:
            - containerPort: 80 # Change if your service runs on a different port
          env:
            - name: NODE_ENV
              value: "Developmet"
      imagePullSecrets:
        - name: servicesecret
---
apiVersion: v1
kind: Service
metadata:
  name: patient-service
  namespace: harsha
spec:
  selector:
    app: patient-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP